#!/usr/bin/env bash
host="cpasilla@${1:-grain}.atmos.colostate.edu"
directory=/zdata2/cpasilla

port=$(shuf -i 20000-40000 -n 1)
#port=$(jot -r 1 20000 40000)
set -x
ssh -L $port:localhost:$port $host \
jupyter-notebook --no-browser --port=$port --notebook-dir=$directory
